% -------------------------------------------------------------------
%  Generated by MATLAB on 6-Sep-2024 22:14:59
%  MATLAB version: 9.7.0.1190202 (R2019b)
% -------------------------------------------------------------------
                             

Ax_OffSet = Simulink.Parameter;
Ax_OffSet.Value = 0;
Ax_OffSet.CoderInfo.StorageClass = 'Model default';
Ax_OffSet.CoderInfo.Alias = '';
Ax_OffSet.CoderInfo.Alignment = -1;
Ax_OffSet.Description = '';
Ax_OffSet.DataType = 'auto';
Ax_OffSet.Min = [];
Ax_OffSet.Max = [];
Ax_OffSet.DocUnits = '';

Ay_OffSet = Simulink.Parameter;
Ay_OffSet.Value = 0;
Ay_OffSet.CoderInfo.StorageClass = 'Model default';
Ay_OffSet.CoderInfo.Alias = '';
Ay_OffSet.CoderInfo.Alignment = -1;
Ay_OffSet.Description = '';
Ay_OffSet.DataType = 'auto';
Ay_OffSet.Min = [];
Ay_OffSet.Max = [];
Ay_OffSet.DocUnits = '';

Caf = Simulink.Parameter;
Caf.Value = 460;
Caf.CoderInfo.StorageClass = 'Model default';
Caf.CoderInfo.Alias = '';
Caf.CoderInfo.Alignment = -1;
Caf.Description = '';
Caf.DataType = 'auto';
Caf.Min = [];
Caf.Max = [];
Caf.DocUnits = '';

Car = Simulink.Parameter;
Car.Value = 440;
Car.CoderInfo.StorageClass = 'Model default';
Car.CoderInfo.Alias = '';
Car.CoderInfo.Alignment = -1;
Car.Description = '';
Car.DataType = 'auto';
Car.Min = [];
Car.Max = [];
Car.DocUnits = '';

Iz = Simulink.Parameter;
Iz.Value = 105;
Iz.CoderInfo.StorageClass = 'Model default';
Iz.CoderInfo.Alias = '';
Iz.CoderInfo.Alignment = -1;
Iz.Description = '';
Iz.DataType = 'auto';
Iz.Min = [];
Iz.Max = [];
Iz.DocUnits = '';

Ki = Simulink.Parameter;
Ki.Value = 1;
Ki.CoderInfo.StorageClass = 'Model default';
Ki.CoderInfo.Alias = '';
Ki.CoderInfo.Alignment = -1;
Ki.Description = '';
Ki.DataType = 'auto';
Ki.Min = [];
Ki.Max = [];
Ki.DocUnits = '';

Kp = Simulink.Parameter;
Kp.Value = 2;
Kp.CoderInfo.StorageClass = 'Model default';
Kp.CoderInfo.Alias = '';
Kp.CoderInfo.Alignment = -1;
Kp.Description = '';
Kp.DataType = 'auto';
Kp.Min = [];
Kp.Max = [];
Kp.DocUnits = '';

Ldwf = Simulink.Parameter;
Ldwf.Value = 1.2;
Ldwf.CoderInfo.StorageClass = 'Model default';
Ldwf.CoderInfo.Alias = '';
Ldwf.CoderInfo.Alignment = -1;
Ldwf.Description = '';
Ldwf.DataType = 'auto';
Ldwf.Min = [];
Ldwf.Max = [];
Ldwf.DocUnits = '';

Ldwr = Simulink.Parameter;
Ldwr.Value = 1.16;
Ldwr.CoderInfo.StorageClass = 'Model default';
Ldwr.CoderInfo.Alias = '';
Ldwr.CoderInfo.Alignment = -1;
Ldwr.Description = '';
Ldwr.DataType = 'auto';
Ldwr.Min = [];
Ldwr.Max = [];
Ldwr.DocUnits = '';

Offset_Angle = Simulink.Parameter;
Offset_Angle.Value = 0;
Offset_Angle.CoderInfo.StorageClass = 'Model default';
Offset_Angle.CoderInfo.Alias = '';
Offset_Angle.CoderInfo.Alignment = -1;
Offset_Angle.Description = '';
Offset_Angle.DataType = 'auto';
Offset_Angle.Min = [];
Offset_Angle.Max = [];
Offset_Angle.DocUnits = '';

Q = Simulink.Parameter;
Q.Value = 0.3;
Q.CoderInfo.StorageClass = 'Model default';
Q.CoderInfo.Alias = '';
Q.CoderInfo.Alignment = -1;
Q.Description = '';
Q.DataType = 'auto';
Q.Min = [];
Q.Max = [];
Q.DocUnits = '';

Qa = Simulink.Parameter;
Qa.Value = 0.1;
Qa.CoderInfo.StorageClass = 'Model default';
Qa.CoderInfo.Alias = '';
Qa.CoderInfo.Alignment = -1;
Qa.Description = '';
Qa.DataType = 'auto';
Qa.Min = [];
Qa.Max = [];
Qa.DocUnits = '';

R = Simulink.Parameter;
R.Value = 0.1;
R.CoderInfo.StorageClass = 'Model default';
R.CoderInfo.Alias = '';
R.CoderInfo.Alignment = -1;
R.Description = '';
R.DataType = 'auto';
R.Min = [];
R.Max = [];
R.DocUnits = '';

Ra = Simulink.Parameter;
Ra.Value = 2;
Ra.CoderInfo.StorageClass = 'Model default';
Ra.CoderInfo.Alias = '';
Ra.CoderInfo.Alignment = -1;
Ra.Description = '';
Ra.DataType = 'auto';
Ra.Min = [];
Ra.Max = [];
Ra.DocUnits = '';

RearRatio = Simulink.Parameter;
RearRatio.Value = 0.8;
RearRatio.CoderInfo.StorageClass = 'Model default';
RearRatio.CoderInfo.Alias = '';
RearRatio.CoderInfo.Alignment = -1;
RearRatio.Description = '';
RearRatio.DataType = 'auto';
RearRatio.Min = [];
RearRatio.Max = [];
RearRatio.DocUnits = '';

Rt = Simulink.Parameter;
Rt.Value = 0.2;
Rt.CoderInfo.StorageClass = 'Model default';
Rt.CoderInfo.Alias = '';
Rt.CoderInfo.Alignment = -1;
Rt.Description = '';
Rt.DataType = 'auto';
Rt.Min = [];
Rt.Max = [];
Rt.DocUnits = '';

TrqRquRate = Simulink.Parameter;
TrqRquRate.Value = 0.1;
TrqRquRate.CoderInfo.StorageClass = 'Model default';
TrqRquRate.CoderInfo.Alias = '';
TrqRquRate.CoderInfo.Alignment = -1;
TrqRquRate.Description = '';
TrqRquRate.DataType = 'auto';
TrqRquRate.Min = [];
TrqRquRate.Max = [];
TrqRquRate.DocUnits = '';

YawRate_OffSet = Simulink.Parameter;
YawRate_OffSet.Value = 0;
YawRate_OffSet.CoderInfo.StorageClass = 'Model default';
YawRate_OffSet.CoderInfo.Alias = '';
YawRate_OffSet.CoderInfo.Alignment = -1;
YawRate_OffSet.Description = '';
YawRate_OffSet.DataType = 'auto';
YawRate_OffSet.Min = [];
YawRate_OffSet.Max = [];
YawRate_OffSet.DocUnits = '';

dwf = Simulink.Parameter;
dwf.Value = 1.2;
dwf.CoderInfo.StorageClass = 'Model default';
dwf.CoderInfo.Alias = '';
dwf.CoderInfo.Alignment = -1;
dwf.Description = '';
dwf.DataType = 'auto';
dwf.Min = [];
dwf.Max = [];
dwf.DocUnits = '';

lf = Simulink.Parameter;
lf.Value = 0.761;
lf.CoderInfo.StorageClass = 'Model default';
lf.CoderInfo.Alias = '';
lf.CoderInfo.Alignment = -1;
lf.Description = '';
lf.DataType = 'auto';
lf.Min = [];
lf.Max = [];
lf.DocUnits = '';

lr = Simulink.Parameter;
lr.Value = 0.831;
lr.CoderInfo.StorageClass = 'Model default';
lr.CoderInfo.Alias = '';
lr.CoderInfo.Alignment = -1;
lr.Description = '';
lr.DataType = 'auto';
lr.Min = [];
lr.Max = [];
lr.DocUnits = '';

m = Simulink.Parameter;
m.Value = 340;
m.CoderInfo.StorageClass = 'Model default';
m.CoderInfo.Alias = '';
m.CoderInfo.Alignment = -1;
m.Description = '';
m.DataType = 'auto';
m.Min = [];
m.Max = [];
m.DocUnits = '';

thr1 = Simulink.Parameter;
thr1.Value = 2;
thr1.CoderInfo.StorageClass = 'Model default';
thr1.CoderInfo.Alias = '';
thr1.CoderInfo.Alignment = -1;
thr1.Description = '';
thr1.DataType = 'auto';
thr1.Min = [];
thr1.Max = [];
thr1.DocUnits = '';

thr2 = Simulink.Parameter;
thr2.Value = 0.5;
thr2.CoderInfo.StorageClass = 'Model default';
thr2.CoderInfo.Alias = '';
thr2.CoderInfo.Alignment = -1;
thr2.Description = '';
thr2.DataType = 'auto';
thr2.Min = [];
thr2.Max = [];
thr2.DocUnits = '';

thr3 = Simulink.Parameter;
thr3.Value = 0.8;
thr3.CoderInfo.StorageClass = 'Model default';
thr3.CoderInfo.Alias = '';
thr3.CoderInfo.Alignment = -1;
thr3.Description = '';
thr3.DataType = 'auto';
thr3.Min = [];
thr3.Max = [];
thr3.DocUnits = '';

thr4 = Simulink.Parameter;
thr4.Value = 0.5;
thr4.CoderInfo.StorageClass = 'Model default';
thr4.CoderInfo.Alias = '';
thr4.CoderInfo.Alignment = -1;
thr4.Description = '';
thr4.DataType = 'auto';
thr4.Min = [];
thr4.Max = [];
thr4.DocUnits = '';

thr5 = Simulink.Parameter;
thr5.Value = -0.5;
thr5.CoderInfo.StorageClass = 'Model default';
thr5.CoderInfo.Alias = '';
thr5.CoderInfo.Alignment = -1;
thr5.Description = '';
thr5.DataType = 'auto';
thr5.Min = [];
thr5.Max = [];
thr5.DocUnits = '';

u = Simulink.Parameter;
u.Value = 0.75;
u.CoderInfo.StorageClass = 'Model default';
u.CoderInfo.Alias = '';
u.CoderInfo.Alignment = -1;
u.Description = '';
u.DataType = 'auto';
u.Min = [];
u.Max = [];
u.DocUnits = '';

